### ISSUE TITLE
Specifying the version of tf and keras required

### ISSUE THREAD

**Issue by ShenduoZhang** [ConorLazarou/medium#1]
# Thanks a lot

First I really like the contest you write. It was inspiring and intuitive. But when I tried to run the code you provided(1_spiral, 2_spiral and uniform_to_norm), I was not able to do that. I am pretty much new to GAN staff. But there seems to be one error keeps popping up all the time. Here's what it looks like as an example,

  File "2_spiral", line 300, in <module>
    _G_loss, _G_accuracy = GAN.train_on_batch(noise, labels)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1175, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_2' with dtype float and shape [?,2]
         [[{{node input_2}}]]

So please attach the environment you use to run those code if you find those code running on your device. Thanks again. Wish you safe(away from corona-virus).

**Comment by RileyLazarou** [comment]
Thanks for the kind words 😄 

It's strange that you're getting that error, since tf.Keras should automatically fill placeholder tensors. This was made using tensorflow==2.1.0 and Python 3.7.6, but Tensorflow 1.15.x should also work fine.

Let me know if updating doesn't fix the problem.
