### ISSUE TITLE
How to know the probability distribution method of own real data.

### ISSUE THREAD

**Issue by Minxiangliu** [ConorLazarou/medium#2]
How to know the probability distribution method of  own real data, such as https://github.com/ConorLazarou/medium/blob/3fae4b997d1faca25e0b7395d5a71da3c2019b03/12020/visualizing_gan_uni2norm/1_uniform_to_normal_1D.py#L123-L124

How to know the value of line 123? Is there any description here? Thank you.

**Comment by RileyLazarou** [comment]
Check out the functions `generate_noise` and `uniform_to_normal`.

`generate_noise` produces independent, uniformly-distributed values in the range [-1, 1] with shape (n, 2) (ie, independent pairs of random numbers). It is a random function.

`uniform_to_normal` is a deterministic function that takes a number in the range [-1, 1] and returns a number in the range (-∞, ∞). This is done using [inverse transform sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling). First, the number in [-1, 1] is rescaled to [0, 1]. Then, it's passed through scipy's percentage point function "ppf" for the normal distribution. These two functions combined is equivalent to sampling from the normal distribution.

**Comment by Minxiangliu** [comment]
Hello, your visualization method aroused my great interest.

I am studying the use of GAN to generate 3D medical images (like CT images), and I try to observe the probability density and the actual probability density of the standard normal distribution.

I do n’t know if it is because the model crashes or is not suitable for using 3D data. The picture I produced is always similar to the following:

![image](https://user-images.githubusercontent.com/30144428/82723999-67cb5e80-9d05-11ea-8a77-04bc7ee5c564.png)

Can you give me any comments or directions? Many thank.
